try {
    console.log('Початок блоку try');
    console.log('Кінець блоку try');
} catch(err) {
    console.log('Catch ігноруєтьсяб оскільк помилки відсутні');
}